### ISSUE TITLE
where is the api?

### ISSUE THREAD

**Issue by forfuns** [adadgio/safari-reader-js#1]
how can I use this js lib for my app?
where is the api , pls !!

**Comment by adadgio** [comment]
You can use this for you app (at your own discretion), because this was taken from the Safari source code.

Their is not API, you have to use it like this 

    var ReaderArticleFinderJS = new ReaderArticleFinder(document);

**Comment by forfuns** [comment]
hi,I try to use this lib on my app, but is not work , no page can use read mode with article

**Comment by forfuns** [comment]
I just use code like this 
```
var ReaderArticleFinderJS = new ReaderArticleFinder(document);
console.log(ReaderArticleFinderJS);
//ReaderArticleFinderJS like no method can use 
```

**Comment by adadgio** [comment]
I just found the source code, i don't really know how to use it (i've tried once and it worked).

And yes, not all pages are readable. Are you able to make it work with this link ? : http://blog.manbolo.com/2012/11/20/using-xcode-opengl-es-frame-capture

**Comment by forfuns** [comment]
@adadgio I just use Readability lib by now, and I need to change the code compatible with out article web page , just make a short content clear

**Comment by adadgio** [comment]
What's the language you are using ? Java / PHP / Javascript ? I might have other options for you.

**Comment by forfuns** [comment]
java and javascript,when java can't do this, I can use thrift to invoke nodejs .

**Comment by forfuns** [comment]
Readability will delete web page document tree dom,when I use that I don't know how to resolve without Readability before

**Comment by adadgio** [comment]
This is the algorithm ported to Java : https://github.com/masukomi/ar90-readability

And here is another one that i have not tested: https://github.com/srijiths/readabilityBUNDLE

**Comment by forfuns** [comment]
oh....
is very helpful,thanks very much :):):):):):):)

**Comment by adadgio** [comment]
No problem ! Good luck.

**Comment by adadgio** [comment]
var ReaderArticleFinderJS = new ReaderArticleFinder(document);
* //var article = ReaderArticleFinderJS.findArticle();
* ReaderArticleFinderJS.isReaderModeAvailable();
* ReaderArticleFinderJS.prepareToTransitionToReader();
