### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by Velocet** [adadgio/safari-reader-js#4]
Hi there, maybe you want to get out a new release since?

**Comment by adadgio** [comment]
Would like too bu beautified file and other files do not match safari version. I was waiting for another PR from you... ;-)

**Comment by Velocet** [comment]
Commited the unmodified version but can't commit anything else since the other file is a direct download from the blog ;)

**Comment by adadgio** [comment]
All right ! Creating a new release.
